#!/bin/sh

TEST=$1
TARGET=$2
TYPE=`echo $TARGET | tr -d 0-9`

# There is no tap driver on OpenBSD
if [ `uname` = "OpenBSD" ] && [ $TYPE = "tap" ];then
	TARGET=`echo $TARGET | sed s/tap/tun/`
	TYPE="tun"
fi

$TEST && ifconfig $TARGET >/dev/null 2>/dev/null
	&& ip tuntap del $TARGET mode $TYPE ; return 0
	|| return 1
